#              The Boron Operating System
# Common makefile for all userland application targets

APP_NAME  = Desktop
# DEBUG  = yes
# DEBUG2 = no

USE_FRIGG = yes
LDFLAGS = -lflanterm -lC++Support

include ../CommonMakefile
