#              The Boron Operating System
# Common makefile for all userland application targets

APP_NAME  = FullScreenTerminal
# DEBUG  = yes
# DEBUG2 = no

CPPFLAGS += -I../libflanterm/source
LDFLAGS = -lflanterm

include ../CommonMakefile
