#              The Boron Operating System
# Common makefile for all userland application targets

APP_NAME  = libC++Support
# DEBUG  = yes
# DEBUG2 = no
IS_LIBRARY = yes

include ../CommonMakefile
