#       The Boron Operating System
# Common makefile for all driver targets

DRIVER_NAME  = hali386
# DRIVER_ENTRY = DriverEntry
# DEBUG  = yes
# DEBUG2 = no
USER_DEFINES = -DIS_HAL -DFLANTERM_FB_DISABLE_CANVAS -DFLANTERM_FB_DISABLE_BUMP_ALLOC

include ../CommonMakefile
