#              The Boron Operating System
# Common makefile for all userland application targets

APP_NAME  = libboron
# DEBUG  = yes
# DEBUG2 = no

IS_LIBRARY = yes
USER_DEFINES = -DIS_BORON_DLL
INCLUDE_LIBBORON = no
LDFLAGS = -e RelocateSelf

include ../CommonMakefile
