#pragma once

enum
{
	STATUS_SUCCESS,
	STATUS_WAITING,
	
	STATUS_ALERTED,
	STATUS_TIMEOUT,
	
	STATUS_RANGE_WAIT           = 0x1000000, // range 0..MAXIMUM_WAIT_BLOCKS
	STATUS_RANGE_ABANDONED_WAIT = 0x1000040, // range 0..MAXIMUM_WAIT_BLOCKS
};
