#              The Boron Operating System
# Common makefile for all userland application targets

APP_NAME  = libflanterm
# DEBUG  = yes
# DEBUG2 = no
IS_LIBRARY = yes

CFLAGS += -DFLANTERM_FB_DISABLE_BUMP_ALLOC

include ../CommonMakefile
