#              The Boron Operating System
# Common makefile for all userland application targets

APP_NAME  = MinimalShell
# DEBUG  = yes
# DEBUG2 = no

LDFLAGS = -lflanterm

include ../CommonMakefile
